add random character generation function and alias

diff --git a/env/bash_functions b/env/bash_functions
--- a/env/bash_functions
+++ b/env/bash_functions
@@ -1,4 +1,4 @@
-# Copyright © 2011-2014 Nick Bargnesi <nick@den-4.com>.  All rights reserved.
+# Copyright © 2011-2016 Nick Bargnesi <nick@den-4.com>.  All rights reserved.
 #
 # bash-environment is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -22,6 +22,18 @@
 #     Aliases
 #     Bindings
 #
+
+# Return 1 if $1 is not found by which, 0 otherwise.
+_need_cmd() {
+    if [ $# -ne 1 ]; then
+        echo "_need_cmd $# -ne 1" >&2
+        return
+    fi
+    if ! which $1 >&/dev/null; then
+        return 1
+    fi
+    return 0
+}
 
 # Use a faster CPU frequency governor
 faster-cpus() {
@@ -147,10 +159,11 @@ function recursively-remove-directories() {
 }
 
 function go-to-warp() {
-    if [ -z $(which sox 2>/dev/null) ]; then
+    _need_cmd sox
+    if [ $? -ne 0 ]; then
         echo "Warp drive only available with Sox."
         echo "Get it here: http://sox.sourceforge.net"
-        return
+        return 1
     fi
     echo "Engaging warp drive."
     play -n -c1 synth whitenoise \
@@ -257,7 +270,7 @@ function local-git-destroy() {
 }
 
 function tag-temp() {
-    which tmsu >/dev/null 2>&1
+    _need_cmd tmsu
     if [ $? -eq 1 ]; then
         echo "tmsu has not been found"
         echo "--"
@@ -267,7 +280,7 @@ function tag-temp() {
 }
 
 function untag-temp() {
-    which tmsu >/dev/null 2>&1
+    _need_cmd tmsu
     if [ $? -eq 1 ]; then
         echo "tmsu has not been found"
         echo "--"
@@ -277,7 +290,7 @@ function untag-temp() {
 }
 
 function purge-temp() {
-    which tmsu >/dev/null 2>&1
+    _need_cmd tmsu
     if [ $? -eq 1 ]; then
         echo "tmsu has not been found"
         echo "--"
@@ -296,7 +309,7 @@ function purge-temp() {
 }
 
 function show-temp() {
-    which tmsu >/dev/null 2>&1
+    _need_cmd tmsu
     if [ $? -eq 1 ]; then
         echo "tmsu has not been found"
         echo "--"
@@ -408,5 +421,22 @@ function own {
     local ID=$(id -u)
     local GROUP=$(id -g)
     sudo chown -R $ID:$GROUP $@
+}
+
+# Use pwgen to generate n characters.
+# E.g.,
+#     rndchars 8
+function rndchars {
+    _need_cmd pwgen
+    # if non-zero, exec to show command not found and return
+    if [ $# -ne 0 ]; then pwgen; return; fi
+    if [ $# -ne 1 ]; then
+        echo "Usage: rndchars <number of characters>"
+        echo
+        echo "Prints some number of characters."
+        return 1
+    fi
+    echo $(pwgen -A0 $1 1)
+    return 0
 }
 
